### ISSUE TITLE
Upstream django commit broke functionality

### ISSUE THREAD

**Issue by guidolongoni** [demiroren-teknoloji/django-admin-autocomplete-list-filter#8]
Hi,
I wanted to report that after [this commit on django main repository](https://github.com/django/django/commit/3071660acfbdf4b5c59457c8e9dc345d5e8894c5) the autocomplete list filter widget no longer works.

On first analysis, when instantiating the `AjaxAutocompleteSelectWidget` object, its `__init__` function calls `super().__init__` passing a "__rel__" keyword argument which is no longer accepted by django `AutocompleteMixin` init function, raising the following exception:

`TypeError: __init__() got an unexpected keyword argument 'rel'`

The offending change is in `django/contrib/admin/widgets.py` file at line __385__.

I haven't delved into it yet, but judging from the commit message, it seems that fix #29138 ("Allowed autocomplete fields to target a custom to_field rather than the PK") is directly related to the choice of replacing the "rel" kwarg with the "field" kwarg, breaking the interface.

**Comment by guidolongoni** [comment]
Update: after the first fix attempt I ran into the issue #4, then I just found out that I was preceded and Guglielmo's pull request #6 solves that and this issue as well.

**Comment by vigo** [comment]
Fixed now! thanks
